package types.enums;

public enum CurrencyEnum {

	INVALID_CURRENCY("INVALID"),

	BLESSED_ORB("blessed"),
	CARTOGRAPHERS_CHISEL("chisel"),
	CHAOS_ORB("chaos"),
	CHROMATIC_ORB("chromatic"),
	DIVINE_ORB("divine"),
	EXALTED_ORB("exalt"),
	MIRROR_OF_KALANDRA("mirror"),
	ORB_OF_ALCHEMY("alch"),
	ORB_OF_ALTERATION("alteration"),
	ORB_OF_AUGMENTATION("augmentation"),
	ORB_OF_CHANCE("chance"),
	VAAL_ORB("vaal"),
	ORB_OF_FUSING("fusing");
	
	//BLESSING_OF_CHAYULA,
	//BLESSING_OF_ESH,
	//BLESSING_OF_TUL,
	//BLESSING_OF_UUL_NETOL,
	//BLESSING_OF_XOPH,
	//ORB_OF_ANNULMENT,
	//ALBINO_RHOA_FEATHER,
	//APPRENTICE_CARTOGRAPHERS_SEAL,
	//APPRENTICE_CARTOGRAPHERS_SEXTANT,
	//ARMOURERS_SCRAP,
	//BLACKSMITHS_WHETSTONE,
	//ORB_OF_REGRET,
	//ORB_OF_SCOURING,
	//ORB_OF_TRANSMUTATION,
	//PORTAL_SCROLL,
	//REGAL_ORB,
	//SCROLL_OF_WISDOM,
	//SILVER_COIN,
	//UNSHAPING_ORB,
	//VAAL_ORB,
	//GEMCUTTERS_PRISM,
	//GLASSBLOWERS_BAUBLE,
	//JEWELLERS_ORB,
	//JOURNEYMAN_CARTOGRAPHERS_SEAL,
	//JOURNEYMAN_CARTOGRAPHERS_SEXTANT,
	//MASTER_CARTOGRAPHERS_SEAL,
	//MASTER_CARTOGRAPHERS_SEXTANT,
	//
	//// Shards
	//ALCHEMY_SHARD,
	//ALTERATION_SHARD,
	//SCROLL_FRAGMENT,	
	//SPLINTER_OF_CHAYULA,	
	//SPLINTER_OF_ESH,	
	//SPLINTER_OF_TUL,	
	//SPLINTER_OF_UUL_NETOL,		
	//SPLINTER_OF_XOPH,	
	//TRANSMUTATION_SHARD,
	//
	//// Harbinger Currency
	//ANCIENT_ORB,
	//ANCIENT_SHARD,
	//ANNULMENT_SHARD,
	//BINDING_SHARD,
	//CHAOS_SHARD,
	//ENGINEERS_ORB,
	//ENGINEERS_SHARD,
	//EXALTED_SHARD,
	//HARBINGERS_ORB,
	//HARBINGERS_SHARD,
	//HORIZON_SHARD,
	//MIRROR_SHARD,
	//ORB_OF_BINDING,
	//ORB_OF_HORIZONS,
	//REGAL_SHARD,
	//
	//// Perandus
	//PERANDUS_COIN,
	
	// Lab
	//OFFERING_TO_THE_GODDESS
	
	private String currString;
	
	private CurrencyEnum(String currString) {
		this.currString = currString;
	}
	
	public String getCurrencyString() {
		return this.currString;
	}
	
	
}
